export enum RouteName {
  'AUTH_LOGIN' = 'AUTH_LOGIN',
  'AUTH_FORGET_PASSWORD' = 'AUTH_FORGET_PASSWORD',

  'PARTICIPANTS_LISTING' = 'PARTICIPANTS_LISTING',
  'WORKER_LISTING' = 'WORKER_LISTING',
  'JOB_LISTING' = 'JOB_LISTING',
  'JOB_DETAILS' = 'JOB_DETAILS',
  'ATTENDANCE_RECORD' = 'ATTENDANCE_RECORD',

  'PROFILE' = 'PROFILE',

  'PAYMENT_METHODS' = 'PAYMENT_METHODS',
  'BILLING_ADDRESS' = 'BILLING_ADDRESS',
  'COLLECT_CARD_DETAILS' = 'COLLECT_CARD_DETAILS',
}
