export enum RouteName {
  'AUTH_LOGIN' = 'AUTH_LOGIN',
  'AUTH_FORGET_PASSWORD' = 'AUTH_FORGET_PASSWORD',

  'PAYMENT_METHODS' = 'PAYMENT_METHODS',
  'COLLECT_CARD_DETAILS' = 'COLLECT_CARD_DETAILS',
  'JOB_LISTING' = 'JOB_LISTING',
}
